# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
